In [180]:
import numpy as np

In [181]:
list = [20,27,9,12,31,17,4,50,39,35]
arr=np.array(list)
print(arr*4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.min(arr))
print(np.max(arr))

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50


In [182]:
greater_than_20=np.array(list)
boolean_mask=greater_than_20 > 20
filtered_array=greater_than_20[boolean_mask]
print(filtered_array)

[27 31 50 39 35]


In [183]:
matrix=[
    [5,12,17,9],
    [8,21,14,3],
    [6,13,19,11],
]
arr=np.array(matrix)
print(arr.shape)
print(arr [1])
print(arr*2)
print(np.mean(arr[0]))
print(np.mean(arr[1]))
print(np.mean(arr[2]))
print(np.mean(arr))
print(np.max(arr[0]))
print(np.min(arr[0]))
print(np.max(arr[1]))
print(np.min(arr[1]))
print(np.max(arr[2]))
print(np.min(arr[2]))
ndarray=arr.flatten()
print(ndarray)
print(np.argmin(ndarray))
print(np.argmax(ndarray))
np.unravel_index([5,12,17,9, 8, 21, 14, 3, 6, 13, 19, 11], (7,5))
greater_than_15=np.array(ndarray)
boolean_mask=greater_than_15 > 15
filtered_array=greater_than_15[boolean_mask]
print(filtered_array)
print(np.sort(ndarray))

(3, 4)
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
10.75
11.5
12.25
11.5
17
5
21
3
19
6
[ 5 12 17  9  8 21 14  3  6 13 19 11]
7
5
[17 21 19]
[ 3  5  6  8  9 11 12 13 14 17 19 21]


In [184]:
# 4: Prime Star Systems
arr=np.array([
    [2,3,5],
    [14,6,8],
    [11,13,17],
    [7,10,13],
])
def is_prime(n):
    if n<2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True
def prime_rows(array):
    ndarray=[]
    for row in array:
        if any(is_prime(n) for n in row):
            ndarray.append(row)
    return np.array(ndarray)
result=prime_rows(arr)
print(result)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [185]:
zero=np.zeros((8,8))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [186]:
def odd_number(rows, cols):
    array=np.zeros((rows,cols))
    for row in range(rows):
        if row % 2 == 1:
            for col in range(cols):
                if col % 2 ==1:
                    array[row, col]=1
        else:
            for col in range(cols):
                if col % 2 == 0:
                    array[row,col]=1
    return array
result=odd_number(8, 8)
print(result)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [187]:
reverse= 1 - result
print(reverse)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [188]:
def expanding_universe(str, int):
    spaces= ' ' * int
    result = spaces.join(str)
    return result
print(expanding_universe("Galaxy", 2))

G  a  l  a  x  y


In [189]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print("begin function")


def second_brightest(arr):
    sorted_array=np.sort(arr)
    new_array=[]
    for row in sorted_array:
        new_array=(sorted_array[:,3])
    return new_array
print(second_brightest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
begin function
[1889 1647 1138 1863 1592]
